version: '3.8'

services:
  db:
    image: postgres:13
    container_name: pg-docker
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: ecommerce-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ecommerce
    depends_on:
      - db
    volumes:
      - ./backend:/app

volumes:
  pgdata:
